# Generated by Django 3.0.4 on 2020-03-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('iduser', models.IntegerField(primary_key=True, serialize=False)),
                ('adress', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('iduser', models.AutoField(primary_key=True, serialize=False)),
                ('nameuser', models.CharField(max_length=45)),
                ('bd', models.DateField()),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
